global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'task-queue'
    static_configs:
      - targets:
          - 'broker1:9091'
          - 'broker2:9093'
          - 'broker3:9095'
    metrics_path: '/metrics'
