global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'task-queue-broker-1'
    static_configs:
      - targets: ['broker-1:9091']
        labels:
          instance: 'broker-1'

  - job_name: 'task-queue-broker-2'
    static_configs:
      - targets: ['broker-2:9091']
        labels:
          instance: 'broker-2'

  - job_name: 'task-queue-broker-3'
    static_configs:
      - targets: ['broker-3:9091']
        labels:
          instance: 'broker-3'
